#!/bin/bash

if [[ "$*" == *"gen_more"* ]]
  then
    for i in {1..1000..1}; do
      TEST=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 4095)
      if [ -f ./tests/sendme_"$i" ]
        then
          echo Il file ./tests/sendme_"$i" già esiste
      else
        echo -n "$TEST" > ./tests/sendme_"$i"
      fi
    done
  echo "Tanti test creati"
elif [[ "$*" == *"gen"* ]]
  then
    for i in {1..10..1}; do
      TEST=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 4095)
      if [ -f ./tests/sendme_"$i" ]
        then
          echo Il file ./tests/sendme_"$i" già esiste
      else
        echo -n "$TEST" > ./tests/sendme_"$i"
      fi
    done
  echo "Test creati"
fi

if [[ "$*" ==  *"clean"* ]]
  then
    rm -f ./tests/*_out
    echo "Test out eliminati"
fi

if [[ "$*" == *"del"* ]]
  then
    rm -f ./tests/sendme_{1..2000}
    echo "Tutti i test sono stati eliminati"
fi